package eu.interiot.intermw.bridge.uaal.client;

public class Body {
    private final static String PREFIX = "http://ontology.universAAL.org/InterIoT.owl#";
    private final static String QUERYDEVICES = 
	    "DESCRIBE ?d WHERE { ?d a <http://ontology.universaal.org/PhThing.owl#Device>}";
    public static final String ID="$%i";
    public static final String CALLBACK="$%c";
    public static final String URI="$%s";
    public static final String TYPE="$%t";
    public static final String TYPE_OBJ="$%o";
    public static final String QUERY="$%q";

    public static final String CREATE_SPACE="{\r\n"
	    + "   \"space\": {\r\n"
	    + "     \"@id\": \""+ID+"\",\r\n"
	    + "     \"callback\": \""+CALLBACK+"\"\r\n"
	    + "   }\r\n"
	    + " }";
    public static final String CREATE_CALLER="{\r\n"
	    + "  \"caller\": {\r\n"
	    + "    \"@id\": \""+ID+"\"\r\n"
	    + "  }\r\n"
	    + " }";
    public static final String CREATE_PUBLISHER="{\r\n"
	    + "  \"publisher\": {\r\n"
	    + "    \"@id\": \""+ID+"\",\r\n"
	    + "    \"providerinfo\": \""
	    + "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\\r\\n"
	    + "@prefix owl: <http://www.w3.org/2002/07/owl#> .\\r\\n"
	    + "@prefix : <http://ontology.universAAL.org/Context.owl#> .\\r\\n"
	    + "<"+URI+"Provider> :myClassesOfEvents (\\r\\n"
	    + "    [\\r\\n"
	    + "      a :ContextEventPattern ;\\r\\n"
	    + "      <http://www.w3.org/2000/01/rdf-schema#subClassOf> [\\r\\n"
	    + "          owl:hasValue <"+URI+"> ;\\r\\n"
	    + "          a owl:Restriction ;\\r\\n"
	    + "          owl:onProperty rdf:subject\\r\\n"
	    + "        ]\\r\\n"
	    + "    ]\\r\\n"
	    + "  ) ;\\r\\n"
	    + "  a :ContextProvider ;\\r\\n"
	    + "  :hasType :controller .\\r\\n"
	    + ":controller a :ContextProviderType .\\r\\n"
	    + "<"+URI+"> a <http://ontology.universaal.org/PhThing.owl#Device>,"
	    + " <http://ontology.universaal.org/PhThing.owl#PhysicalThing> .\"\r\n"
	    + "  } \r\n"
	    + " }";   
    public static final String CREATE_CALLEE_GET="{\r\n"
	    + "  \"callee\": {\r\n"
	    + "    \"@id\": \""+ID+"\",\r\n"
	    + "     \"callback\": \""+CALLBACK+"\",\r\n"
	    + "     \"profile\": \"@prefix pvn: <http://ontology.universAAL.org/uAAL.owl#> .\\r\\n"
	    + "@prefix ns: <http://www.daml.org/services/owl-s/1.1/Profile.owl#> .\\r\\n"
	    + "@prefix ns1: <http://www.daml.org/services/owl-s/1.1/Process.owl#> .\\r\\n"
	    + "@prefix owl: <http://www.w3.org/2002/07/owl#> .\\r\\n"
	    + "@prefix ns2: <http://www.daml.org/services/owl-s/1.1/Service.owl#> .\\r\\n"
	    + "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\\r\\n"
	    + "@prefix ns3: <http://ontology.universAAL.org/PhThing.owl#> .\\r\\n"
	    + "@prefix ns4: <http://ontology.universAAL.org/Device.owl#> .\\r\\n"
	    + "@prefix : <http://ontology.universAAL.org/Workbench.owl#> .\\r\\n"
	    + "_:BN000000 ns2:presentedBy <"+URI+"DeviceServer> ;\\r\\n"
	    + "  a ns:Profile ;\\r\\n"
	    + "  ns:has_process <"+URI+"DeviceServerProcess> ;\\r\\n"
	    + "  ns:hasResult [\\r\\n"
	    + "    ns1:withOutput (\\r\\n"
	    + "      [\\r\\n"
	    + "        a ns1:OutputBinding ;\\r\\n"
	    + "        ns1:toParam <"+PREFIX+"output> ;\\r\\n"
	    + "        ns1:valueForm \\\"\\\"\\\"\\r\\n"
	    + "          @prefix : <http://ontology.universAAL.org/uAAL.owl#> .\\r\\n"
	    + "          _:BN000000 a :PropertyPath ;\\r\\n"
	    + "            :thePath (\\r\\n"
	    + "              <http://ontology.universAAL.org/PhThing.owl#controls>\\r\\n"
	    + "            ) .\\r\\n"
	    + "          \\\"\\\"\\\"^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#XMLLiteral>\\r\\n"
	    + "      ]\\r\\n"
	    + "    ) ;\\r\\n"
	    + "    a ns1:Result\\r\\n"
	    + "  ] ;\\r\\n"
	    + "  ns:hasOutput (\\r\\n"
	    + "    <"+PREFIX+"output>\\r\\n"
	    + "  ) .\\r\\n"
	    + "<"+URI+"> a <"+TYPE+"> ,\\r\\n"
	    + "    ns3:Device ,\\r\\n"
	    + "    ns3:PhysicalThing .\\r\\n"
	    + "<"+URI+"DeviceServer> a ns3:DeviceService ;\\r\\n"
	    + "  pvn:instanceLevelRestrictions (\\r\\n"
	    + "    [\\r\\n"
	    + "      owl:hasValue <"+URI+"> ;\\r\\n"
	    + "      a owl:Restriction ;\\r\\n"
	    + "      owl:onProperty ns3:controls\\r\\n"
	    + "    ]\\r\\n"
	    + "    [\\r\\n"
	    + "      a owl:Restriction ;\\r\\n"
	    + "      owl:allValuesFrom <"+TYPE+"> ;\\r\\n"
	    + "      owl:onProperty ns3:controls\\r\\n"
	    + "    ]\\r\\n"
	    + "  ) ;\\r\\n"
	    + "  ns2:presents _:BN000000 ;\\r\\n"
	    + "  pvn:numberOfValueRestrictions \\\"0\\\"^^xsd:int .\\r\\n"
	    + "<"+PREFIX+"output> a ns1:Output ;\\r\\n"
	    + "  ns1:parameterType \\\""+TYPE+"\\\"^^xsd:anyURI .\\r\\n"
	    + "<"+TYPE+"> a owl:Class .\"\r\n"
	    + "  }\r\n"
	    + " }";
    public static final String CREATE_CALLEE_GETVALUE="{\r\n"
	    + "  \"callee\": {\r\n"
	    + "    \"@id\": \""+ID+"\",\r\n"
	    + "     \"callback\": \""+CALLBACK+"\",\r\n"
	    + "     \"profile\": \"@prefix pvn: <http://ontology.universAAL.org/uAAL.owl#> .\\r\\n"
	    + "@prefix ns: <http://www.daml.org/services/owl-s/1.1/Profile.owl#> .\\r\\n"
	    + "@prefix ns1: <http://www.daml.org/services/owl-s/1.1/Process.owl#> .\\r\\n"
	    + "@prefix ns2: <http://ontology.universAAL.org/Workbench.owl#> .\\r\\n"
	    + "@prefix ns3: <http://www.daml.org/services/owl-s/1.1/Service.owl#> .\\r\\n"
	    + "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\\r\\n"
	    + "@prefix ns4: <http://ontology.universAAL.org/PhThing.owl#> .\\r\\n"
	    + "@prefix ns5: <http://ontology.universAAL.org/Device.owl#> .\\r\\n"
	    + "@prefix : <http://www.w3.org/2002/07/owl#> .\\r\\n"
	    + "_:BN000000 ns3:presentedBy <"+URI+"ValueServer> ;\\r\\n"
	    + "  a ns:Profile ;\\r\\n"
	    + "  ns:has_process <"+URI+"ValueServerProcess> ;\\r\\n"
	    + "  ns:hasResult [\\r\\n"
	    + "    ns1:withOutput (\\r\\n"
	    + "      [\\r\\n"
	    + "        a ns1:OutputBinding ;\\r\\n"
	    + "        ns1:toParam <"+PREFIX+"output> ;\\r\\n"
	    + "        ns1:valueForm \\\"\\\"\\\"\\r\\n"
	    + "          @prefix : <http://ontology.universAAL.org/uAAL.owl#> .\\r\\n"
	    + "          _:BN000000 a :PropertyPath ;\\r\\n"
	    + "            :thePath (\\r\\n"
	    + "              <http://ontology.universAAL.org/PhThing.owl#controls>\\r\\n"
	    + "              <http://ontology.universAAL.org/Device.owl#hasValue>\\r\\n"
	    + "            ) .\\r\\n"
	    + "          \\\"\\\"\\\"^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#XMLLiteral>\\r\\n"
	    + "      ]\\r\\n"
	    + "    ) ;\\r\\n"
	    + "    a ns1:Result\\r\\n"
	    + "  ] ;\\r\\n"
	    + "  ns:hasOutput (\\r\\n"
	    + "    <"+PREFIX+"output>\\r\\n"
	    + "  ) .\\r\\n"
	    + "<"+URI+"> a <"+TYPE+"> ,\\r\\n"
	    + "    ns4:Device ,\\r\\n"
	    + "    ns4:PhysicalThing .\\r\\n"
	    + "<"+URI+"ValueServer> a ns4:DeviceService ;\\r\\n"
	    + "  pvn:instanceLevelRestrictions (\\r\\n"
	    + "    [\\r\\n"
	    + "      :hasValue <"+URI+"> ;\\r\\n"
	    + "      a :Restriction ;\\r\\n"
	    + "      :onProperty ns4:controls\\r\\n"
	    + "    ]\\r\\n"
	    + "    [\\r\\n"
	    + "      a :Restriction ;\\r\\n"
	    + "      :allValuesFrom [\\r\\n"
	    + "        a :Restriction ;\\r\\n"
	    + "        :allValuesFrom <"+TYPE_OBJ+"> ;\\r\\n"
	    + "        :onProperty ns5:hasValue\\r\\n"
	    + "      ] ;\\r\\n"
	    + "      :onProperty ns4:controls\\r\\n"
	    + "    ]\\r\\n"
	    + "  ) ;\\r\\n"
	    + "  ns3:presents _:BN000000 ;\\r\\n"
	    + "  pvn:numberOfValueRestrictions \\\"0\\\"^^xsd:int .\\r\\n"
	    + "<"+PREFIX+"output> a ns1:Output ;\\r\\n"
	    + "  ns1:parameterType \\\""+TYPE_OBJ+"\\\"^^xsd:anyURI .\"\r\n"
	    + "  }\r\n"
	    + " }";
    public static final String CREATE_SUBSCRIBER="{\r\n"
	    + "  \"subscriber\": {\r\n"
	    + "    \"@id\": \""+ID+"\",\r\n"
	    + "     \"callback\": \""+CALLBACK+"\",\r\n"
	    + "    \"pattern\": \""
	    + "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\\r\\n"
	    + "@prefix : <http://www.w3.org/2002/07/owl#> .\\r\\n"
	    + "_:BN000000 a <http://ontology.universAAL.org/Context.owl#ContextEventPattern> ;\\r\\n"
	    + "  <http://www.w3.org/2000/01/rdf-schema#subClassOf> [\\r\\n"
	    + "      a :Restriction ;\\r\\n"
	    + "      :hasValue <"+URI+"> ;\\r\\n"
	    + "      :onProperty rdf:subject\\r\\n"
	    + "    ] .\\r\\n"
	    + "<"+URI+"> a <http://ontology.universaal.org/PhThing.owl#Device>,"
	    + " <http://ontology.universaal.org/PhThing.owl#PhysicalThing> .\"\r\n"
	    + "  }\r\n"
	    + " }";    
    public static final String CALL_QUERY="@prefix ns: <http://www.daml.org/services/owl-s/1.1/Profile.owl#> ."
	    + "@prefix owl: <http://www.w3.org/2002/07/owl#> ."
	    + "@prefix pvn: <http://ontology.universAAL.org/uAAL.owl#> ."
	    + "@prefix ns1: <http://ontology.universAAL.org/InterIoT.owl#> ."
	    + "@prefix ns2: <http://www.daml.org/services/owl-s/1.1/Service.owl#> ."
	    + "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> ."
	    + "@prefix ns3: <http://ontology.universAAL.org/ContextHistory.owl#> ."
	    + "@prefix : <http://www.daml.org/services/owl-s/1.1/Process.owl#> ."
	    + "_:BN000000 a pvn:ServiceRequest ;"
	    + "pvn:requiredResult ["
	    + ":withOutput ("
	    + "["
	    + "        a :OutputBinding ;"
	    + "        :toParam ns1:output1 ;"
	    + "        :valueForm \"\"\""
	    + "          @prefix : <http://ontology.universAAL.org/Service.owl#> ."
	    + "          _:BN000000 a :PropertyPath ;"
	    + "            :thePath ("
	    + "              <http://ontology.universAAL.org/ContextHistory.owl#returns>"
	    + "            ) ."
	    + "          \"\"\"^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#XMLLiteral>"
	    + "      ]"
	    + "    ) ;"
	    + "    a :Result"
	    + "  ] ;"
	    + "  pvn:requestedService ns1:serviceX ."
	    + "ns1:output1 a :Output ."
	    + "ns1:serviceX a ns3:ContextHistoryService ;"
	    + "  pvn:instanceLevelRestrictions ("
	    + "    ["
	    + "      owl:hasValue \""+QUERY+"\"^^xsd:string ;"
	    + "      a owl:Restriction ;"
	    + "      owl:onProperty ns3:processes"
	    + "    ]"
	    + "  ) ;"
	    + "  ns2:presents ["
	    + "    ns2:presentedBy ns1:serviceX ;"
	    + "    a ns:Profile ;"
	    + "    ns:has_process ns1:serviceXProcess"
	    + "  ] ;"
	    + "  pvn:numberOfValueRestrictions \"1\"^^xsd:int .";
    public static final String CALL_GETALLDEVICES=CALL_QUERY.replace(QUERY, QUERYDEVICES);
    public static final String CALL_GETDEVICE="@prefix ns: <http://www.daml.org/services/owl-s/1.1/Profile.owl#> ."
	    + "prefix ns1: <http://ontology.universaal.org/PhThing.owl#> ."
	    + "@prefix owl: <http://www.w3.org/2002/07/owl#> ."
	    + "@prefix pvn: <http://ontology.universAAL.org/uAAL.owl#> ."
	    + "@prefix ns2: <http://www.daml.org/services/owl-s/1.1/Process.owl#> ."
	    + "@prefix ns3: <http://www.daml.org/services/owl-s/1.1/Service.owl#> ."
	    + "@prefix : <http://ontology.universAAL.org/Workbench.owl#> ."
	    + "_:BN000000 a pvn:ServiceRequest ;"
	    + "  pvn:requiredResult ["
	    + "    ns2:withOutput ("
	    + "      ["
	    + "        a ns2:OutputBinding ;"
	    + "        ns2:toParam :output1 ;"
	    + "        ns2:valueForm \"\"\""
	    + "          @prefix : <http://ontology.universAAL.org/Service.owl#> ."
	    + "          _:BN000000 a :PropertyPath ;"
	    + "            :thePath ("
	    + "              <http://ontology.universaal.org/PhThing.owl#controls>"
	    + "            ) ."
	    + "          \"\"\"^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#XMLLiteral>"
		    + "      ]"
	    + "    ) ;"
	    + "    a ns2:Result"
	    + "  ] ;"
	    + "  pvn:requestedService :serviceX ."
	    + "<"+URI+"> a <"+TYPE+"> ,"
	    + "    ns1:Device ,"
	    + "    ns1:PhysicalThing ."
	    + ":output1 a ns2:Output ."
	    + ":serviceX a ns1:DeviceService ;"
	    + "  pvn:instanceLevelRestrictions ("
	    + "    ["
	    + "      owl:hasValue <"+URI+"> ;"
	    + "      a owl:Restriction ;"
	    + "      owl:onProperty ns1:controls"
	    + "    ]"
  	    + ") ;"
	    + "  ns3:presents ["
	    + "    ns3:presentedBy :serviceX ;"
	    + "    a ns:Profile ;"
	    + "    ns:has_process :serviceXProcess"
	    + "  ] ;"
	    + "  pvn:numberOfValueRestrictions \"1\"^^<http://www.w3.org/2001/XMLSchema#int> .";
}